/**
 * organization
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface OrganizationGetProjectUsagesRequest {
    /**
     * Project IDs
     */
    projects: string[];
    /**
     * Starting time (in seconds from epoch) for collecting statistics
     */
    from_date: string;
    /**
     * Ending time (in seconds from epoch) for collecting statistics. Pass null for   now
     */
    to_date: string;
    include_development: boolean;
    usage_fields: string[];
}
